# Generated by Django 4.1 on 2024-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='inventory_images/')),
                ('timeupdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
