# Generated by Django 4.1 on 2024-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_management', '0005_alter_inventory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
