# Generated by Django 4.1 on 2024-03-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_management', '0008_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_added',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='name',
        ),
    ]
