# Generated by Django 4.1 on 2024-03-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_management', '0011_rename_note_stockitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
