# Generated by Django 4.1 on 2024-04-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_management', '0016_alter_stock_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categ',
        ),
    ]
