# Generated by Django 4.1 on 2024-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_management', '0019_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='qauntity',
            field=models.IntegerField(default=1),
        ),
    ]
