# Generated by Django 4.1 on 2024-05-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturent.order'),
        ),
    ]
