# Generated by Django 4.1 on 2024-05-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0004_client_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturent.order'),
        ),
    ]
