# Generated by Django 4.1 on 2024-06-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0005_alter_client_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
