# Generated by Django 4.1 on 2024-06-11 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authenticate', '0002_alter_clientuser_email_alter_clientuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='client_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='client_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
