# Generated by Django 4.1 on 2024-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qauntity',
            field=models.IntegerField(default=1),
        ),
    ]
