# Generated by Django 4.1 on 2024-06-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0005_alter_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
